### ISSUE TITLE
Status of the project seems stalled.

### ISSUE THREAD

**Issue by essic** [pointu-l/projet-innovant#3]
Can you give here an overview of the features you plan to develop and their status ? (Complete, In Progress, Not Started)

Thanks.

**Comment by legalquentin** [comment]
First off, sorry for the delayed response.
Due to other projects deadlines, we had to put the state of the project on standby,
Development will resume today.

**Completed tasks or unlikely to change are :**
- User authentication, and login
- User profile

**In-progress stuff :**
- Adds, new Offers

**As for the next upcoming features :** 
- Documenting the API on swagger
- Adding new routes and methods for the upcoming features such as :
( ads interactions, trip overview, user feed )

Please make to sure to stay tuned on [the other repo](https://github.com/pointu-l/projet-innovant-angular.git) 

Thanks for the feedback !
